# Generated by Django 5.1 on 2024-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-posted_date']},
        ),
        migrations.AddField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Deadline to apply for the job', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='requirements',
            field=models.TextField(default='none', help_text='List of job requirements'),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default='none', help_text='List of job responsibilities'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, help_text='Salary range or amount', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
