# Generated by Django 5.1 on 2024-08-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=200)),
                ('payment_status', models.BooleanField(default=False)),
                ('ref', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-payment_date',),
            },
        ),
    ]
