# Generated by Django 5.1 on 2024-08-29 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_status',
        ),
    ]
