# Generated by Django 5.1 on 2024-08-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_payment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
