# Generated by Django 5.1 on 2024-08-31 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0003_alter_job_options_job_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_cert', models.FileField(blank=True, null=True, upload_to='license_cert/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agree', models.BooleanField()),
                ('date', models.DateField()),
                ('signature', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=100)),
                ('date_started', models.DateField()),
                ('date_completed', models.DateField()),
                ('certificates', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('position_applied_for', models.CharField(max_length=100)),
                ('examination_date', models.DateField()),
                ('chest_xray', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=50, null=True)),
                ('heart', models.CharField(blank=True, max_length=255, null=True)),
                ('stool', models.CharField(blank=True, max_length=255, null=True)),
                ('haemoglobin', models.CharField(blank=True, max_length=50, null=True)),
                ('abdomen', models.CharField(blank=True, max_length=255, null=True)),
                ('vision', models.CharField(blank=True, max_length=255, null=True)),
                ('hearing', models.CharField(blank=True, max_length=255, null=True)),
                ('lungs', models.CharField(blank=True, max_length=255, null=True)),
                ('urine', models.CharField(blank=True, max_length=255, null=True)),
                ('sickling', models.CharField(blank=True, max_length=255, null=True)),
                ('extremities', models.CharField(blank=True, max_length=255, null=True)),
                ('certification_status', models.CharField(choices=[('fit', 'Medically Fit'), ('fit_with_condition', 'Medically Fit with Condition'), ('unfit', 'Medically Unfit')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_disability', models.BooleanField()),
                ('disability_details', models.TextField(blank=True, null=True)),
                ('medical_condition', models.BooleanField()),
                ('condition_details', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('birthplace', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced/Separated'), ('widow', 'Widow')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_occupation', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('mothers_occupation', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_occupation', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=50)),
                ('contact_address', models.CharField(max_length=255)),
                ('passport_picture', models.ImageField(blank=True, null=True, upload_to='passport_pictures/')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_choice', models.CharField(blank=True, choices=[('western', 'Western Region'), ('central', 'Central Region'), ('ashanti', 'Ashanti Region'), ('brong', 'Brong Ahafo Region'), ('upperWest', 'Upper West Region')], max_length=20, null=True)),
                ('second_choice', models.CharField(blank=True, choices=[('western', 'Western Region'), ('central', 'Central Region'), ('ashanti', 'Ashanti Region'), ('brong', 'Brong Ahafo Region'), ('upperWest', 'Upper West Region')], max_length=20, null=True)),
                ('third_choice', models.CharField(blank=True, choices=[('western', 'Western Region'), ('central', 'Central Region'), ('ashanti', 'Ashanti Region'), ('brong', 'Brong Ahafo Region'), ('upperWest', 'Upper West Region')], max_length=20, null=True)),
                ('fourth_choice', models.CharField(blank=True, choices=[('western', 'Western Region'), ('central', 'Central Region'), ('ashanti', 'Ashanti Region'), ('brong', 'Brong Ahafo Region'), ('upperWest', 'Upper West Region')], max_length=20, null=True)),
                ('fifth_choice', models.CharField(blank=True, choices=[('western', 'Western Region'), ('central', 'Central Region'), ('ashanti', 'Ashanti Region'), ('brong', 'Brong Ahafo Region'), ('upperWest', 'Upper West Region')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('addendum', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.addendum')),
                ('declaration', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.declaration')),
                ('educational_background', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.educationalbackground')),
                ('medical_certification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.medicalcertification')),
                ('medical_history', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.medicalhistory')),
                ('personal_information', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.personalinformation')),
                ('posting_preference', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.postingpreference')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulatory_body', models.CharField(max_length=100)),
                ('registration_pin', models.CharField(max_length=50)),
                ('date_received', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
