# Generated by Django 5.1 on 2024-09-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='passport_picture',
            field=models.ImageField(upload_to='passport_pictures/'),
        ),
    ]
