# Generated by Django 5.1 on 2024-08-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(default='none'),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(default='none', max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='0245325587', max_length=15),
        ),
    ]
