# Generated by Django 5.1 on 2024-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addendum',
            name='license_cert',
        ),
        migrations.AddField(
            model_name='addendum',
            name='other_cert',
            field=models.FileField(blank=True, null=True, upload_to='other_cert/'),
        ),
    ]
