# Generated by Django 5.1 on 2024-09-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0002_remove_addendum_license_cert_addendum_other_cert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='facilities',
            new_name='region_name',
        ),
        migrations.RemoveField(
            model_name='postingpreference',
            name='first_choice',
        ),
        migrations.RemoveField(
            model_name='postingpreference',
            name='region',
        ),
        migrations.RemoveField(
            model_name='postingpreference',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='postingpreference',
            name='third_choice',
        ),
        migrations.RemoveField(
            model_name='region',
            name='name',
        ),
        migrations.AddField(
            model_name='postingpreference',
            name='first_choice_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_choice_region', to='application_portal.region'),
        ),
        migrations.AddField(
            model_name='postingpreference',
            name='second_choice_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choice_region', to='application_portal.region'),
        ),
        migrations.AddField(
            model_name='postingpreference',
            name='third_choice_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_choice_region', to='application_portal.region'),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(default='none', max_length=50)),
                ('town_name', models.CharField(default='none', max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='application_portal.region')),
            ],
        ),
        migrations.AddField(
            model_name='postingpreference',
            name='first_choice_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_choice_facility', to='application_portal.facility'),
        ),
        migrations.AddField(
            model_name='postingpreference',
            name='second_choice_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_choice_facility', to='application_portal.facility'),
        ),
        migrations.AddField(
            model_name='postingpreference',
            name='third_choice_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_choice_facility', to='application_portal.facility'),
        ),
    ]
