# Generated by Django 5.1 on 2024-09-19 06:12

import application_portal.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0004_application_application_id_application_job_and_more'),
        ('jobs', '0003_alter_job_options_job_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='professional_registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='application_portal.professionalregistration'),
        ),
        migrations.AlterField(
            model_name='application',
            name='addendum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_portal.addendum'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_id',
            field=models.CharField(default=application_portal.models.generate_application_id, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='educational_background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_portal.educationalbackground'),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='application',
            name='medical_certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_portal.medicalcertification'),
        ),
        migrations.AlterField(
            model_name='application',
            name='medical_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_portal.medicalhistory'),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_portal.personalinformation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='posting_preference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application_portal.postingpreference'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
