# Generated by Django 5.1 on 2024-09-20 06:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0006_personalinformation_ghana_card_number_and_more'),
        ('jobs', '0003_alter_job_options_job_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='job_title',
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'job')},
        ),
    ]
