# Generated by Django 5.1 on 2024-09-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0007_remove_personalinformation_job_title_and_more'),
        ('jobs', '0003_alter_job_options_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingpreference',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
