# Generated by Django 5.1 on 2024-09-20 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0008_postingpreference_job'),
        ('jobs', '0003_alter_job_options_job_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postingpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='postingpreference',
            constraint=models.UniqueConstraint(fields=('user', 'job'), name='unique_user_job_preference'),
        ),
    ]
