# Generated by Django 5.1 on 2024-09-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0009_alter_postingpreference_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('under review', 'Under Review'), ('pending', 'Pending'), ('accepted', 'Accepted')], max_length=50),
        ),
    ]
