# Generated by Django 5.1 on 2024-09-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_portal', '0010_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
